trigger:
- main

pool:
  name: GiftOfTheGivers-Pool12

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- script: dotnet --info
  displayName: 'Display .NET information'

- script: dotnet restore GiftOfTheGivers/GiftOfTheGivers/GiftOfTheGivers.csproj
  displayName: 'Restore dependencies'

- script: dotnet build GiftOfTheGivers/GiftOfTheGivers/GiftOfTheGivers.csproj --configuration Release --no-restore
  displayName: 'Build application'

- script: dotnet test GiftOfTheGivers/GiftOfTheGivers/GiftOfTheGivers.csproj --configuration Release --no-build
  displayName: 'Run tests'